plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Ryan Moore
description: This is my Jekyll website that is running simple.css
lang: en
locale: en
url: "https://blog.mooreanalysis.com"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20
